LabWork1_AleksandraMihaylova
georgedobrev/Blankfactor_SQL pull request #100
Opened 2023-05-15 08:20 UTC by aleksandramihaylova

2023-05-15 21:13 UTC, sslavova requested changes
Just a small update on managers table

2023-05-15 21:13 UTC, sslavova commented on LabWork1_AleksandraMihaylova/Script_LabWork1_AleksandraMihaylova.sql
> +
Just add not null constraint in email and remove default value of hire_date

2023-05-16 06:00 UTC, aleksandramihaylova commented on LabWork1_AleksandraMihaylova/Script_LabWork1_AleksandraMihaylova.sql
> +
I edited it. Thank you!

2023-05-26 08:44 UTC, sslavova requested changes

2023-05-26 08:44 UTC, sslavova commented on LabWork1_AleksandraMihaylova/Script_LabWork1_AleksandraMihaylova.sql
>  );
The hire date in employees table must have a default value.

2023-05-29 07:51 UTC, sslavova approved these changes

2023-05-29 08:04 UTC, merged