LabWork4_AleksandraMihaylova
georgedobrev/Blankfactor_SQL pull request #103
Opened 2023-05-15 11:49 UTC by aleksandramihaylova

2023-05-15 21:21 UTC, sslavova requested changes

2023-05-15 21:21 UTC, sslavova commented on LabWork4_AleksandraMihaylova/Script_LabWork4_AleksandraMihaylova.sql
> +
Add order by in below query

2023-05-15 21:21 UTC, sslavova commented on LabWork4_AleksandraMihaylova/Script_LabWork4_AleksandraMihaylova.sql
> +
Below round is not needed but it's not an issue even if you leave it this way

2023-05-16 06:12 UTC, aleksandramihaylova commented on LabWork4_AleksandraMihaylova/Script_LabWork4_AleksandraMihaylova.sql
> +
I added it. Thank you

2023-05-16 19:15 UTC, sslavova approved these changes

2023-05-17 06:10 UTC, merged