Create LabWork7RobertProdanov.sql
georgedobrev/Blankfactor_SQL pull request #128
Opened 2023-05-17 07:43 UTC by RobertProdanov03

2023-05-19 11:14 UTC, sandarova requested changes

2023-05-19 11:14 UTC, sandarova commented on LabWork7/LabWork7RobertProdanov.sql
> +
Task 3: 
Write  a query to retrieve information about the countries from the country dataset and the sum of the population of their cities from the city database. Leave in the result set only the countries with population in their cities over 1 million people and present the result starting from the largest number.

2023-05-26 06:37 UTC, RobertProdanov03 commented on LabWork7/LabWork7RobertProdanov.sql
> +
I added the task

2023-05-29 08:03 UTC, sandarova approved these changes

2023-05-29 08:06 UTC, merged