LabWork4_MilchoKasmetov
georgedobrev/Blankfactor_SQL pull request #48
Opened 2023-05-11 16:10 UTC by Kasmetov

2023-05-16 14:31 UTC, sslavova requested changes

2023-05-16 20:06 UTC, sslavova requested changes

2023-05-16 20:06 UTC, sslavova commented on LabWork4_MilchoKasmetov/LabWork4_MilchoKasmetov.sql
> +
The previous query was correct. The comment was related to the next query. Apologies.

2023-05-16 20:06 UTC, sslavova commented on LabWork4_MilchoKasmetov/LabWork4_MilchoKasmetov.sql
In below query we need to calculate and round the total surface area. Please add correct aggregations and grouping.
Sorry but I am not able to add the comment after the query...

2023-05-18 08:22 UTC, sandarova approved these changes

2023-05-18 10:07 UTC, sandarova approved these changes

2023-05-18 10:09 UTC, sslavova approved these changes

2023-05-18 11:42 UTC, merged