LabWork5_Hristiyana_Shopova
georgedobrev/Blankfactor_SQL pull request #76
Opened 2023-05-12 08:47 UTC by hristiyanaSh

2023-05-15 20:38 UTC, sslavova requested changes

2023-05-15 20:38 UTC, sslavova commented on Script.sql
> +
Here you need to take only the countries with N/A life expectancy. I would also add the names of these countries

2023-05-15 20:38 UTC, sslavova commented on Script.sql
> +
The version with the case statements is correct, however the version with nested if statements has a syntax error. Fix the brackets

2023-05-16 21:05 UTC, sslavova requested changes

2023-05-16 21:05 UTC, sslavova commented on Script.sql
> +
Brackets are still not fixed, please test your code before committing.

2023-05-18 10:58 UTC, hristiyanaSh commented on Script.sql
> +
I corrected the brackets.

2023-05-26 07:47 UTC, sslavova requested changes

2023-05-26 07:47 UTC, sslavova commented on Script.sql
>  end as CountrySize from country ;
1. Above query is ok now, but please apply the same logic in the other query with nested if statements.
2. Below code (line 33-55) is related to Lab work 4 - remove it from Lab work 5.

2023-05-29 07:54 UTC, sslavova approved these changes

2023-05-29 10:14 UTC, sslavova approved these changes

2023-05-29 10:14 UTC, closed without merging