LabWork4_VladislavMilchov
georgedobrev/Blankfactor_SQL pull request #81
Opened 2023-05-12 11:29 UTC by VladislavMilchov

2023-05-16 08:49 UTC, sslavova requested changes

2023-05-16 08:49 UTC, sslavova commented on LabWork4_VladislavMilchov/Script.sql
> +
Below query is wrong - it will produce NULL.

2023-05-16 08:49 UTC, sslavova commented on LabWork4_VladislavMilchov/Script.sql
> +
Add rounding in below query.
Also add aliases to all aggregation functions.

2023-05-16 08:49 UTC, sslavova commented on LabWork4_VladislavMilchov/Script.sql
> +
It's a good practice to add upper to the columns when you don't know if the values inside consist of lower or upper cases. MySQL accepts both 'NLD' or 'nld', but most of the databases are case sensitive so there it's better to do it this way:
UPPER(CountryCode) = 'NLD'

2023-05-19 13:52 UTC, VladislavMilchov commented on LabWork4_VladislavMilchov/Script.sql
> +
Fixed

2023-05-25 19:39 UTC, sslavova approved these changes
Good job! :)

2023-05-26 11:22 UTC, merged