LabWork6_Dame_Stoilovski
georgedobrev/Blankfactor_SQL pull request #90
Opened 2023-05-14 14:51 UTC by DameStoilovski99

2023-05-15 18:51 UTC, sslavova requested changes

2023-05-15 18:51 UTC, sslavova commented on Lab_Work_6_Dame_Stoilovski/Lab_Work_6_Dame_Stoilovski.sql
> +
Keep in mind that the where clause is filtering away rows where the left join doesn't succeed. 
You won't see that here because you are taking only the countries that have 3 or more official languages but if you remove that filter (just for test) you'll see the difference.
Currently the logic is correct because you actually don't need the countries that are different than 'T' but be careful when using left joins with where clause.
Also change the sum to count - otherwise when you remove the filter for the official languages you'll see that last few countries that do not have any official languages are NULLs instead of 0.

2023-05-25 19:16 UTC, sslavova requested changes

2023-05-25 19:16 UTC, sslavova commented on Lab_Work_6_Dame_Stoilovski/Lab_Work_6_Dame_Stoilovski.sql
> +
Before final approve of the code, please just remove the unnecessary query, change the string to be in single quotes (in MySQL this is working fine, but it's a good practice to use single quotes since other languages won't accept that syntax) and decide what to change - left join to inner join, or move the IsOfficial = 'T' in the join condition - both are acceptable :)

2023-05-26 07:45 UTC, DameStoilovski99 commented on Lab_Work_6_Dame_Stoilovski/Lab_Work_6_Dame_Stoilovski.sql
> +
> Before final approve of the code, please just remove the unnecessary query, change the string to be in single quotes (in MySQL this is working fine, but it's a good practice to use single quotes since other languages won't accept that syntax) and decide what to change - left join to inner join, or move the IsOfficial = 'T' in the join condition - both are acceptable :)

Thank you for the good explanation. :)
I fixed it, I think everything is okay now.

2023-05-26 08:23 UTC, sslavova approved these changes

2023-05-26 08:23 UTC, merged