LabWork7_Dame_Stoilovski
georgedobrev/Blankfactor_SQL pull request #91
Opened 2023-05-14 14:51 UTC by DameStoilovski99

2023-05-19 11:20 UTC, sandarova requested changes

2023-05-19 11:20 UTC, sandarova commented on LabWork7_Dame_Stoilovski/Lab_Work_7_Dame_Stoilovski.sql
> +)
Select only the columns required

2023-05-25 19:27 UTC, sslavova approved these changes

2023-05-26 07:39 UTC, sandarova approved these changes

2023-05-26 07:40 UTC, merged