LabWork2_AleksandraMihaylova
georgedobrev/Blankfactor_SQL pull request #97
Opened 2023-05-15 07:33 UTC by aleksandramihaylova

2023-05-15 21:05 UTC, sslavova requested changes
Just one small update needed for the government form, everything else looks good :)

2023-05-15 21:05 UTC, sslavova commented on LabWork2_AleksandraMihaylova /LabWork2_AleksandraMihaylova.sql
> +
Just a small fix - keep in mind you need all kinds of republics :)

2023-05-16 06:06 UTC, aleksandramihaylova commented on LabWork2_AleksandraMihaylova /LabWork2_AleksandraMihaylova.sql
> +
I edited the file!

2023-05-16 19:09 UTC, sslavova approved these changes
Looks good now :)

2023-05-17 06:10 UTC, merged